tailwind.config = {
      darkMode: "class",
      theme: {
        extend: {
          colors: {
            "on-primary-container": "#AEBBC0",
            "on-secondary-fixed-variant": "#050B11",
            "inverse-primary": "#1B3443",
            "inverse-on-surface": "#050B11",
            "outline": "#AEBBC0",
            "stone-mist": "#AEBBC0",
            "on-tertiary": "#050B11",
            "surface-container-lowest": "#050B11",
            "marine-navy": "#102432",
            "on-error": "#690005",
            "inverse-surface": "#F2F0E9",
            "surface-dim": "#08131C",
            "error-container": "#93000a",
            "surface": "#08131C",
            "sand-pearl": "#F2F0E9",
            "surface-container": "#102432",
            "on-primary-fixed": "#050B11",
            "on-tertiary-fixed-variant": "#102432",
            "cliff-verdant": "#78A9AE",
            "primary": "#78A9AE",
            "tertiary-fixed": "#A8C9C8",
            "secondary-fixed-dim": "#78A9AE",
            "error": "#ffb4ab",
            "surface-bright": "#294653",
            "secondary-container": "#102432",
            "outline-variant": "#1B3443",
            "on-secondary-fixed": "#050B11",
            "on-surface-variant": "#AEBBC0",
            "on-secondary-container": "#A8C9C8",
            "on-error-container": "#ffdad6",
            "golden-hour": "#D8C29A",
            "on-primary-fixed-variant": "#102432",
            "sunset-amber": "#BFA57C",
            "on-surface": "#F2F0E9",
            "primary-fixed-dim": "#78A9AE",
            "on-primary": "#050B11",
            "on-background": "#F2F0E9",
            "surface-tint": "#78A9AE",
            "tertiary-fixed-dim": "#78A9AE",
            "secondary": "#A8C9C8",
            "surface-container-high": "#1B3443",
            "tertiary-container": "#102432",
            "primary-container": "#102432",
            "abyss-black": "#050B11",
            "background": "#08131C",
            "tertiary": "#78A9AE",
            "surface-container-low": "#102432",
            "on-secondary": "#050B11",
            "primary-fixed": "#A8C9C8",
            "secondary-fixed": "#A8C9C8",
            "surface-variant": "#1B3443",
            "on-tertiary-container": "#A8C9C8",
            "on-tertiary-fixed": "#050B11",
            "surface-container-highest": "#294653",
            "midnight-ink": "#08131C",
            "deep-marine": "#102432",
            "blue-slate": "#1B3443",
            "mist-slate": "#294653",
            "sea-glass-blue": "#78A9AE",
            "pale-aqua": "#A8C9C8",
            "soft-champagne": "#D8C29A",
            "oyster-white": "#F2F0E9",
            "mist-gray": "#AEBBC0",
            "ink-black": "#050B11"
          },
          borderRadius: {
            "DEFAULT": "0.25rem",
            "lg": "0.5rem",
            "xl": "0.75rem",
            "2xl": "1rem",
            "3xl": "1.5rem",
            "full": "9999px"
          },
          spacing: {
            "space-xs": "0.25rem",
            "space-sm": "0.5rem",
            "space-md": "1rem",
            "space-lg": "1.5rem",
            "space-xl": "2.5rem",
            "space-2xl": "4rem",
            "space-3xl": "6rem",
            "margin": "1.25rem",
            "margin-tablet": "2.5rem",
            "margin-desktop": "5rem"
          },
          fontFamily: {
            "serif-display": ["Cinzel", "EB Garamond", "serif"],
            "headline-lg": ["EB Garamond", "serif"],
            "headline-md": ["EB Garamond", "serif"],
            "headline-sm": ["EB Garamond", "serif"],
            "display-hero": ["EB Garamond", "serif"],
            "body-lg": ["Plus Jakarta Sans", "sans-serif"],
            "body-md": ["Plus Jakarta Sans", "sans-serif"],
            "body-sm": ["Plus Jakarta Sans", "sans-serif"],
            "label-caps": ["Plus Jakarta Sans", "sans-serif"],
            "title-sm": ["Plus Jakarta Sans", "sans-serif"],
            "title-lg": ["Plus Jakarta Sans", "sans-serif"]
          }
        }
      }
    };
